language: c++

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-5
      - mpich2 
      - mpich2-doc
      - libmpich-dev
        #- libcr-dev 


before_script:
  - CC=gcc-5
  - CXX=g++-5

script: 
  - ./install.sh
  
